export interface SeedIngrediente {
  nome: string;
  reparto: string;
  unitaDefault: string;
  alias?: string[];
}

/** Seed v1 — ~180 ingredienti di cucina italiana, reparti in stile Esselunga.
 * Nessuna noce/frutta a guscio per scelta (allergia in famiglia, RF13 di ANALISI.md):
 * se un giorno servisse aggiungerne una, va fatto solo manualmente dall'utente in app. */
export const SEED_VERSION = 1;

export const SEED_INGREDIENTI: SeedIngrediente[] = [
  // ── Ortofrutta ──
  { nome: "Zucchine", reparto: "Ortofrutta", unitaDefault: "1 kg" },
  { nome: "Melanzane", reparto: "Ortofrutta", unitaDefault: "1 kg" },
  { nome: "Pomodori", reparto: "Ortofrutta", unitaDefault: "1 kg", alias: ["pomodori da insalata"] },
  { nome: "Pomodorini", reparto: "Ortofrutta", unitaDefault: "500 g", alias: ["pomodorini ciliegino", "datterini"] },
  { nome: "Insalata mista", reparto: "Ortofrutta", unitaDefault: "1 busta" },
  { nome: "Lattuga", reparto: "Ortofrutta", unitaDefault: "1 pz" },
  { nome: "Rucola", reparto: "Ortofrutta", unitaDefault: "1 busta" },
  { nome: "Spinaci freschi", reparto: "Ortofrutta", unitaDefault: "500 g", alias: ["spinaci"] },
  { nome: "Bietole", reparto: "Ortofrutta", unitaDefault: "500 g" },
  { nome: "Cime di rapa", reparto: "Ortofrutta", unitaDefault: "500 g", alias: ["cimarapa", "friarielli freschi"] },
  { nome: "Broccoli", reparto: "Ortofrutta", unitaDefault: "1 kg" },
  { nome: "Cavolfiore", reparto: "Ortofrutta", unitaDefault: "1 pz" },
  { nome: "Carote", reparto: "Ortofrutta", unitaDefault: "1 kg" },
  { nome: "Patate", reparto: "Ortofrutta", unitaDefault: "1 kg" },
  { nome: "Cipolle", reparto: "Ortofrutta", unitaDefault: "1 kg" },
  { nome: "Cipollotto", reparto: "Ortofrutta", unitaDefault: "1 mazzo" },
  { nome: "Aglio", reparto: "Ortofrutta", unitaDefault: "1 testa" },
  { nome: "Sedano", reparto: "Ortofrutta", unitaDefault: "1 costa" },
  { nome: "Peperoni", reparto: "Ortofrutta", unitaDefault: "1 kg" },
  { nome: "Zucca", reparto: "Ortofrutta", unitaDefault: "1 kg" },
  { nome: "Funghi champignon", reparto: "Ortofrutta", unitaDefault: "250 g", alias: ["champignon", "funghi freschi"] },
  { nome: "Basilico", reparto: "Ortofrutta", unitaDefault: "1 mazzo" },
  { nome: "Prezzemolo", reparto: "Ortofrutta", unitaDefault: "1 mazzo" },
  { nome: "Limoni", reparto: "Ortofrutta", unitaDefault: "1 kg" },
  { nome: "Arance", reparto: "Ortofrutta", unitaDefault: "1 kg" },
  { nome: "Mele", reparto: "Ortofrutta", unitaDefault: "1 kg" },
  { nome: "Banane", reparto: "Ortofrutta", unitaDefault: "1 kg" },
  { nome: "Pere", reparto: "Ortofrutta", unitaDefault: "1 kg" },
  { nome: "Uva", reparto: "Ortofrutta", unitaDefault: "500 g" },
  { nome: "Fragole", reparto: "Ortofrutta", unitaDefault: "500 g" },
  { nome: "Kiwi", reparto: "Ortofrutta", unitaDefault: "1 kg" },
  { nome: "Avocado", reparto: "Ortofrutta", unitaDefault: "1 pz" },
  { nome: "Finocchi", reparto: "Ortofrutta", unitaDefault: "1 kg" },
  { nome: "Radicchio", reparto: "Ortofrutta", unitaDefault: "1 pz" },
  { nome: "Porri", reparto: "Ortofrutta", unitaDefault: "1 pz" },

  // ── Banco frigo ──
  { nome: "Mozzarella", reparto: "Banco frigo", unitaDefault: "2×125 g", alias: ["fior di latte"] },
  { nome: "Mozzarella di bufala", reparto: "Banco frigo", unitaDefault: "1 conf." },
  { nome: "Parmigiano Reggiano", reparto: "Banco frigo", unitaDefault: "100 g", alias: ["parmigiano"] },
  { nome: "Grana Padano", reparto: "Banco frigo", unitaDefault: "100 g", alias: ["grana"] },
  { nome: "Ricotta", reparto: "Banco frigo", unitaDefault: "250 g" },
  { nome: "Burro", reparto: "Banco frigo", unitaDefault: "250 g" },
  { nome: "Uova", reparto: "Banco frigo", unitaDefault: "6 pz", alias: ["uovo"] },
  { nome: "Yogurt bianco", reparto: "Banco frigo", unitaDefault: "4×125 g" },
  { nome: "Yogurt greco", reparto: "Banco frigo", unitaDefault: "2×150 g" },
  { nome: "Panna da cucina", reparto: "Banco frigo", unitaDefault: "200 ml" },
  { nome: "Latte fresco", reparto: "Banco frigo", unitaDefault: "1 l" },
  { nome: "Gorgonzola", reparto: "Banco frigo", unitaDefault: "200 g" },
  { nome: "Pecorino", reparto: "Banco frigo", unitaDefault: "150 g" },
  { nome: "Scamorza", reparto: "Banco frigo", unitaDefault: "200 g" },
  { nome: "Stracchino", reparto: "Banco frigo", unitaDefault: "200 g", alias: ["crescenza"] },
  { nome: "Formaggio spalmabile", reparto: "Banco frigo", unitaDefault: "200 g" },
  { nome: "Prosciutto cotto", reparto: "Banco frigo", unitaDefault: "100 g" },
  { nome: "Prosciutto crudo", reparto: "Banco frigo", unitaDefault: "100 g" },
  { nome: "Speck", reparto: "Banco frigo", unitaDefault: "100 g" },
  { nome: "Bresaola", reparto: "Banco frigo", unitaDefault: "100 g" },
  { nome: "Salame", reparto: "Banco frigo", unitaDefault: "1 conf." },
  { nome: "Pancetta", reparto: "Banco frigo", unitaDefault: "100 g", alias: ["pancetta a cubetti", "guanciale"] },
  { nome: "Würstel", reparto: "Banco frigo", unitaDefault: "1 conf." },
  { nome: "Pasta fresca all'uovo", reparto: "Banco frigo", unitaDefault: "250 g", alias: ["tagliatelle fresche"] },
  { nome: "Tortellini freschi", reparto: "Banco frigo", unitaDefault: "250 g" },

  // ── Macelleria e pesce ──
  { nome: "Petto di pollo", reparto: "Macelleria e pesce", unitaDefault: "500 g" },
  { nome: "Cosce di pollo", reparto: "Macelleria e pesce", unitaDefault: "1 kg" },
  { nome: "Macinato di manzo", reparto: "Macelleria e pesce", unitaDefault: "500 g", alias: ["carne macinata"] },
  { nome: "Macinato misto", reparto: "Macelleria e pesce", unitaDefault: "500 g" },
  { nome: "Fettine di vitello", reparto: "Macelleria e pesce", unitaDefault: "500 g" },
  { nome: "Salsiccia", reparto: "Macelleria e pesce", unitaDefault: "500 g" },
  { nome: "Bistecca di manzo", reparto: "Macelleria e pesce", unitaDefault: "500 g" },
  { nome: "Spezzatino di manzo", reparto: "Macelleria e pesce", unitaDefault: "500 g" },
  { nome: "Filetto di maiale", reparto: "Macelleria e pesce", unitaDefault: "500 g" },
  { nome: "Tacchino a fette", reparto: "Macelleria e pesce", unitaDefault: "500 g" },
  { nome: "Merluzzo fresco", reparto: "Macelleria e pesce", unitaDefault: "500 g" },
  { nome: "Salmone fresco", reparto: "Macelleria e pesce", unitaDefault: "400 g" },
  { nome: "Gamberi", reparto: "Macelleria e pesce", unitaDefault: "500 g" },
  { nome: "Cozze", reparto: "Macelleria e pesce", unitaDefault: "1 kg" },
  { nome: "Vongole", reparto: "Macelleria e pesce", unitaDefault: "1 kg" },
  { nome: "Calamari", reparto: "Macelleria e pesce", unitaDefault: "500 g" },
  { nome: "Tonno fresco", reparto: "Macelleria e pesce", unitaDefault: "400 g" },
  { nome: "Orata", reparto: "Macelleria e pesce", unitaDefault: "1 pz" },
  { nome: "Branzino", reparto: "Macelleria e pesce", unitaDefault: "1 pz" },
  { nome: "Sogliola", reparto: "Macelleria e pesce", unitaDefault: "1 pz" },

  // ── Surgelati ──
  { nome: "Piselli surgelati", reparto: "Surgelati", unitaDefault: "500 g" },
  { nome: "Spinaci surgelati", reparto: "Surgelati", unitaDefault: "500 g" },
  { nome: "Verdure miste surgelate", reparto: "Surgelati", unitaDefault: "500 g", alias: ["misto verdure"] },
  { nome: "Misto mare surgelato", reparto: "Surgelati", unitaDefault: "500 g" },
  { nome: "Gamberetti surgelati", reparto: "Surgelati", unitaDefault: "300 g" },
  { nome: "Filetti di merluzzo surgelati", reparto: "Surgelati", unitaDefault: "400 g" },
  { nome: "Patate surgelate", reparto: "Surgelati", unitaDefault: "1 kg", alias: ["patatine surgelate"] },
  { nome: "Pizza surgelata", reparto: "Surgelati", unitaDefault: "1 pz" },
  { nome: "Gelato", reparto: "Surgelati", unitaDefault: "1 conf." },
  { nome: "Frutti di bosco surgelati", reparto: "Surgelati", unitaDefault: "300 g" },
  { nome: "Minestrone surgelato", reparto: "Surgelati", unitaDefault: "500 g" },
  { nome: "Friarielli surgelati", reparto: "Surgelati", unitaDefault: "400 g", alias: ["broccoletti surgelati"] },
  { nome: "Hamburger surgelati", reparto: "Surgelati", unitaDefault: "1 conf." },
  { nome: "Bastoncini di pesce", reparto: "Surgelati", unitaDefault: "1 conf." },
  { nome: "Spinaci in cubetti", reparto: "Surgelati", unitaDefault: "500 g" },

  // ── Dispensa ──
  { nome: "Spaghetti", reparto: "Dispensa", unitaDefault: "500 g", alias: ["pasta lunga"] },
  { nome: "Penne", reparto: "Dispensa", unitaDefault: "500 g", alias: ["pasta corta"] },
  { nome: "Orecchiette", reparto: "Dispensa", unitaDefault: "500 g" },
  { nome: "Tagliatelle secche", reparto: "Dispensa", unitaDefault: "250 g" },
  { nome: "Riso", reparto: "Dispensa", unitaDefault: "1 kg" },
  { nome: "Riso per risotti", reparto: "Dispensa", unitaDefault: "1 kg", alias: ["arborio", "carnaroli"] },
  { nome: "Farina 00", reparto: "Dispensa", unitaDefault: "1 kg", alias: ["farina"] },
  { nome: "Farina integrale", reparto: "Dispensa", unitaDefault: "1 kg" },
  { nome: "Zucchero", reparto: "Dispensa", unitaDefault: "1 kg" },
  { nome: "Sale fino", reparto: "Dispensa", unitaDefault: "1 kg" },
  { nome: "Sale grosso", reparto: "Dispensa", unitaDefault: "1 kg" },
  { nome: "Olio extravergine d'oliva", reparto: "Dispensa", unitaDefault: "1 l", alias: ["olio evo", "olio d'oliva"] },
  { nome: "Aceto balsamico", reparto: "Dispensa", unitaDefault: "1 conf." },
  { nome: "Aceto di vino", reparto: "Dispensa", unitaDefault: "1 conf." },
  { nome: "Passata di pomodoro", reparto: "Dispensa", unitaDefault: "700 g" },
  { nome: "Pomodori pelati", reparto: "Dispensa", unitaDefault: "400 g", alias: ["pelati"] },
  { nome: "Concentrato di pomodoro", reparto: "Dispensa", unitaDefault: "1 tubetto" },
  { nome: "Tonno sott'olio", reparto: "Dispensa", unitaDefault: "1 conf.", alias: ["tonno in scatola"] },
  { nome: "Acciughe sott'olio", reparto: "Dispensa", unitaDefault: "1 conf.", alias: ["alici"] },
  { nome: "Olive verdi", reparto: "Dispensa", unitaDefault: "1 conf." },
  { nome: "Olive nere", reparto: "Dispensa", unitaDefault: "1 conf." },
  { nome: "Capperi", reparto: "Dispensa", unitaDefault: "1 vasetto" },
  { nome: "Ceci in scatola", reparto: "Dispensa", unitaDefault: "1 conf." },
  { nome: "Fagioli in scatola", reparto: "Dispensa", unitaDefault: "1 conf." },
  { nome: "Lenticchie secche", reparto: "Dispensa", unitaDefault: "500 g" },
  { nome: "Ceci secchi", reparto: "Dispensa", unitaDefault: "500 g" },
  { nome: "Brodo granulare", reparto: "Dispensa", unitaDefault: "1 conf." },
  { nome: "Dado vegetale", reparto: "Dispensa", unitaDefault: "1 conf." },
  { nome: "Pane grattugiato", reparto: "Dispensa", unitaDefault: "1 conf." },
  { nome: "Cornflakes", reparto: "Dispensa", unitaDefault: "1 conf." },
  { nome: "Biscotti secchi", reparto: "Dispensa", unitaDefault: "1 conf." },
  { nome: "Marmellata", reparto: "Dispensa", unitaDefault: "1 vasetto" },
  { nome: "Miele", reparto: "Dispensa", unitaDefault: "1 vasetto" },
  { nome: "Cacao amaro in polvere", reparto: "Dispensa", unitaDefault: "1 conf." },
  { nome: "Caffè macinato", reparto: "Dispensa", unitaDefault: "250 g" },
  { nome: "Orzo perlato", reparto: "Dispensa", unitaDefault: "500 g" },
  { nome: "Farro", reparto: "Dispensa", unitaDefault: "500 g" },
  { nome: "Cous cous", reparto: "Dispensa", unitaDefault: "500 g" },
  { nome: "Polenta", reparto: "Dispensa", unitaDefault: "500 g", alias: ["farina di mais"] },
  { nome: "Pesto alla genovese", reparto: "Dispensa", unitaDefault: "1 vasetto" },
  { nome: "Maionese", reparto: "Dispensa", unitaDefault: "1 conf." },
  { nome: "Senape", reparto: "Dispensa", unitaDefault: "1 conf." },
  { nome: "Ketchup", reparto: "Dispensa", unitaDefault: "1 conf." },
  { nome: "Zafferano", reparto: "Dispensa", unitaDefault: "1 bustina" },
  { nome: "Lievito per dolci", reparto: "Dispensa", unitaDefault: "1 bustina" },
  { nome: "Lievito di birra secco", reparto: "Dispensa", unitaDefault: "1 bustina" },
  { nome: "Gnocchi di patate", reparto: "Dispensa", unitaDefault: "500 g" },

  // ── Forno ──
  { nome: "Pane comune", reparto: "Forno", unitaDefault: "500 g", alias: ["pane"] },
  { nome: "Pane in cassetta", reparto: "Forno", unitaDefault: "1 conf." },
  { nome: "Grissini", reparto: "Forno", unitaDefault: "1 conf." },
  { nome: "Taralli", reparto: "Forno", unitaDefault: "1 conf." },
  { nome: "Focaccia", reparto: "Forno", unitaDefault: "1 pz" },
  { nome: "Piadine", reparto: "Forno", unitaDefault: "1 conf." },
  { nome: "Panini per hamburger", reparto: "Forno", unitaDefault: "1 conf." },
  { nome: "Cracker", reparto: "Forno", unitaDefault: "1 conf." },
  { nome: "Fette biscottate", reparto: "Forno", unitaDefault: "1 conf." },
  { nome: "Brioche confezionate", reparto: "Forno", unitaDefault: "1 conf." },
  { nome: "Pandoro", reparto: "Forno", unitaDefault: "1 pz" },
  { nome: "Panettone", reparto: "Forno", unitaDefault: "1 pz" },
  { nome: "Pane carasau", reparto: "Forno", unitaDefault: "1 conf." },
  { nome: "Pane azzimo", reparto: "Forno", unitaDefault: "1 conf." },
  { nome: "Crostatine", reparto: "Forno", unitaDefault: "1 conf." },

  // ── Bevande ──
  { nome: "Acqua naturale", reparto: "Bevande", unitaDefault: "6×1,5 l" },
  { nome: "Acqua frizzante", reparto: "Bevande", unitaDefault: "6×1,5 l" },
  { nome: "Vino rosso", reparto: "Bevande", unitaDefault: "1 bottiglia" },
  { nome: "Vino bianco", reparto: "Bevande", unitaDefault: "1 bottiglia" },
  { nome: "Birra", reparto: "Bevande", unitaDefault: "1 conf." },
  { nome: "Succo d'arancia", reparto: "Bevande", unitaDefault: "1 l" },
  { nome: "Succo di frutta multivitaminico", reparto: "Bevande", unitaDefault: "1 l" },
  { nome: "Tè freddo", reparto: "Bevande", unitaDefault: "1,5 l" },
  { nome: "Aranciata", reparto: "Bevande", unitaDefault: "1,5 l" },
  { nome: "Cola", reparto: "Bevande", unitaDefault: "1,5 l" },
  { nome: "Latte a lunga conservazione", reparto: "Bevande", unitaDefault: "1 l", alias: ["latte uht"] },
  { nome: "Caffè in capsule", reparto: "Bevande", unitaDefault: "1 conf." },
  { nome: "Camomilla in bustine", reparto: "Bevande", unitaDefault: "1 conf." },
  { nome: "Tè in bustine", reparto: "Bevande", unitaDefault: "1 conf." },
  { nome: "Spremuta d'arancia confezionata", reparto: "Bevande", unitaDefault: "1 l" },

  // ── Casa e igiene ──
  { nome: "Detersivo per piatti", reparto: "Casa e igiene", unitaDefault: "1 conf." },
  { nome: "Detersivo per lavatrice", reparto: "Casa e igiene", unitaDefault: "1 conf." },
  { nome: "Ammorbidente", reparto: "Casa e igiene", unitaDefault: "1 conf." },
  { nome: "Carta igienica", reparto: "Casa e igiene", unitaDefault: "1 conf." },
  { nome: "Tovaglioli di carta", reparto: "Casa e igiene", unitaDefault: "1 conf." },
  { nome: "Carta da cucina", reparto: "Casa e igiene", unitaDefault: "1 conf." },
  { nome: "Sacchetti per la spesa", reparto: "Casa e igiene", unitaDefault: "1 conf." },
  { nome: "Sacchi per la spazzatura", reparto: "Casa e igiene", unitaDefault: "1 conf." },
  { nome: "Spugne per piatti", reparto: "Casa e igiene", unitaDefault: "1 conf." },
  { nome: "Dentifricio", reparto: "Casa e igiene", unitaDefault: "1 pz" },
  { nome: "Shampoo", reparto: "Casa e igiene", unitaDefault: "1 pz" },
  { nome: "Sapone per le mani", reparto: "Casa e igiene", unitaDefault: "1 pz" },
];
